spring:
  application:
    name: gateway
    jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            lob:
              non_contextual_creation: true
  jmx:
    enabled: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:3300/userdb
    username: postgres
    password: root

server:
  port: 8080
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

zuul:
  sensitive-headers: Cookie
